jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Configure pip caching
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        path: ~/.cache/pip
        restore-keys: '${{ runner.os }}-pip-

          '
    - name: Install Python dependencies
      run: 'python -m pip install -r requirements.txt

        '
    - name: Update README
      run: 'python build_readme.py

        cat README.md'
    - name: Commit and push if changed
      run: 'git diff

        git config --global user.email "actions@users.noreply.github.com"

        git config --global user.name "README-bot"

        git add -A

        git commit -m "Updated content" || exit 0

        git push'
name: Build README
'on':
- workflow_dispatch
permissions: write-all
